// <auto-generated />
using System;
using AspNetCore.Courses.Section15.Infrastructures.DAL.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Courses.Section15.Infrastructures.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    partial class PersonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCore.Courses.Section15.Infrastructures.Infrastructures.ModelsEntities.CountryEntityModel", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("44456690-ec3b-4b52-8621-71f79712f19a"),
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryID = new Guid("33078766-f09b-4f5b-81b9-567d332ac32f"),
                            CountryName = "Macedonia"
                        },
                        new
                        {
                            CountryID = new Guid("c76f4ade-16ee-436e-9115-03f3280fb4b2"),
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryID = new Guid("7b46eb99-c4f0-4f8f-837f-95177b512bb1"),
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryID = new Guid("e6e323e6-a122-401f-b3b9-ff7dfc3df3de"),
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryID = new Guid("8a02d751-bf41-4601-9694-0b31c8d120b6"),
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryID = new Guid("ca6034c4-d106-40a4-b3f7-680268054261"),
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryID = new Guid("77089c9c-29e2-44da-bb96-b279ed51fd4c"),
                            CountryName = "China"
                        },
                        new
                        {
                            CountryID = new Guid("496c2b48-fdf7-4064-8b26-0e60689cbf44"),
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryID = new Guid("23c556ad-28df-45b6-a066-25f80017eb6d"),
                            CountryName = "Indonesia"
                        });
                });

            modelBuilder.Entity("AspNetCore.Courses.Section15.Infrastructures.Infrastructures.ModelsEntities.PersonEntityModel", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ReceiveNewLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("5ff09c86-4eef-455f-8001-69c93da8a34a"),
                            Address = "3 Hayes Street",
                            CountryID = new Guid("44456690-ec3b-4b52-8621-71f79712f19a"),
                            DateOfBirth = new DateTime(2004, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "rtomlett0@gnu.org",
                            Gender = "Male",
                            PersonName = "Rickey Tomlett",
                            ReceiveNewLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("86e7bdcf-f574-436e-ad94-c851c595db51"),
                            Address = "51 Waubesa Junction",
                            CountryID = new Guid("33078766-f09b-4f5b-81b9-567d332ac32f"),
                            DateOfBirth = new DateTime(2002, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "mmccullen1@sina.com.cn",
                            Gender = "Male",
                            PersonName = "Mattie McCullen",
                            ReceiveNewLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("895e817b-7510-49e5-833e-758f74604997"),
                            Address = "7 Almo Parkway",
                            CountryID = new Guid("c76f4ade-16ee-436e-9115-03f3280fb4b2"),
                            DateOfBirth = new DateTime(1990, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "cwingatt2@t.co",
                            Gender = "Female",
                            PersonName = "Charlot Wingatt",
                            ReceiveNewLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("05eb218b-6fe2-4b5c-8f9b-acf057ce522e"),
                            Address = "772 Eastwood Park",
                            CountryID = new Guid("7b46eb99-c4f0-4f8f-837f-95177b512bb1"),
                            DateOfBirth = new DateTime(2012, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "djeratt3@homestead.com",
                            Gender = "Female",
                            PersonName = "Dulci Jeratt",
                            ReceiveNewLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("2ad19535-1ec9-47d0-9264-9a0d67e98ed3"),
                            Address = "98554 Paget Terrace",
                            CountryID = new Guid("e6e323e6-a122-401f-b3b9-ff7dfc3df3de"),
                            DateOfBirth = new DateTime(2012, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "mloisi4@mit.edu",
                            Gender = "Female",
                            PersonName = "Maris Loisi",
                            ReceiveNewLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("4247b2e5-f1b2-4a15-b8af-abc8d9b6e0ea"),
                            Address = "122 Fulton Terrace",
                            CountryID = new Guid("8a02d751-bf41-4601-9694-0b31c8d120b6"),
                            DateOfBirth = new DateTime(1992, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "kwombwell5@i2i.jp",
                            Gender = "Female",
                            PersonName = "Konstance Wombwell",
                            ReceiveNewLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("00223335-4cbd-4bad-995a-428246d990aa"),
                            Address = "299 Reindahl Street",
                            CountryID = new Guid("ca6034c4-d106-40a4-b3f7-680268054261"),
                            DateOfBirth = new DateTime(1992, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "cfarryann6@cbslocal.com",
                            Gender = "Female",
                            PersonName = "Clary Farryann",
                            ReceiveNewLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("0a532dfd-6d9c-4639-81d1-06d0740b1393"),
                            Address = "8 Nelson Lane",
                            CountryID = new Guid("77089c9c-29e2-44da-bb96-b279ed51fd4c"),
                            DateOfBirth = new DateTime(1992, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "fmichal7@surveymonkey.com",
                            Gender = "Male",
                            PersonName = "Frederic Michal",
                            ReceiveNewLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("e9745dd4-859d-4665-bd96-a8a68811c070"),
                            Address = "65 Londonderry Place",
                            CountryID = new Guid("496c2b48-fdf7-4064-8b26-0e60689cbf44"),
                            DateOfBirth = new DateTime(1991, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "cgravells8@shinystat.com",
                            Gender = "Female",
                            PersonName = "Cicely Gravells",
                            ReceiveNewLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("c34e4488-5f88-4291-9e2f-f534cd5de9e9"),
                            Address = "7524 Linden Lane",
                            CountryID = new Guid("23c556ad-28df-45b6-a066-25f80017eb6d"),
                            DateOfBirth = new DateTime(1993, 8, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Email = "gkuschek9@icq.com",
                            Gender = "Female",
                            PersonName = "Gianna Kuschek",
                            ReceiveNewLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
